// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8csnRmc74nkbVLHw7gIt52-CHEu1oiFI',
    appId: '1:554964531740:web:db0f96f4480bd672a13dd9',
    messagingSenderId: '554964531740',
    projectId: 'money-saver-b6c7a',
    authDomain: 'money-saver-b6c7a.firebaseapp.com',
    storageBucket: 'money-saver-b6c7a.appspot.com',
    measurementId: 'G-6L5FPWY4Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7elLLw1Id7J2D7NvDPHUPXhcxFVaF9gM',
    appId: '1:554964531740:android:5e10a563d411450ea13dd9',
    messagingSenderId: '554964531740',
    projectId: 'money-saver-b6c7a',
    storageBucket: 'money-saver-b6c7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxlu15k7e5hDRWQGr8eoohAECfulRVQPs',
    appId: '1:554964531740:ios:e1fe023011fb689aa13dd9',
    messagingSenderId: '554964531740',
    projectId: 'money-saver-b6c7a',
    storageBucket: 'money-saver-b6c7a.appspot.com',
    androidClientId: '554964531740-o54kptuuffmbbp2mjtuqumat942ej7ed.apps.googleusercontent.com',
    iosClientId: '554964531740-shk6j0aqhl53hhe0aqe5hr9af8kuiod3.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneySaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxlu15k7e5hDRWQGr8eoohAECfulRVQPs',
    appId: '1:554964531740:ios:e1fe023011fb689aa13dd9',
    messagingSenderId: '554964531740',
    projectId: 'money-saver-b6c7a',
    storageBucket: 'money-saver-b6c7a.appspot.com',
    androidClientId: '554964531740-o54kptuuffmbbp2mjtuqumat942ej7ed.apps.googleusercontent.com',
    iosClientId: '554964531740-shk6j0aqhl53hhe0aqe5hr9af8kuiod3.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneySaver',
  );
}
